//
//  RonnieFileName.swift
//  
//
//  Created by Daniel Weatrowski on 5/22/22.
//

import Foundation

/// Collection of all filenames generated or read by all Ronnie commands. Add new file names for new commands to
/// this collection.
enum FileName: String, CaseIterable {
    /// Totals filename, used by `MonthlyTotals` to generate or load totals files
    case totals = "totals.csv"
    /// Transactions filename for the transactions file generated by the `Generate` command.
    case transactionsGenerated = "transactions_GENERATED.csv"
    ///  Transactions csv loaded into `MonthlyTotals` to calculate all totals files.
    case transactions = "transactions.csv"
    /// Settings json file
    case settings = "settings.json"
}
